version: '3.8'

services:
  # 1. Dịch vụ Cơ sở dữ liệu MySQL 9.3.0
  db:
    image: mysql:9.3.0
    container_name: academic_db
    restart: always
    environment:
      MYSQL_DATABASE: academic_management_system
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:7.2-alpine
    container_name: academic_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_network

  # 3. Dịch vụ Spring Boot Backend (Java 21 + Maven)
  api:
    build:
      context: . # Trỏ đến thư mục hiện tại chứa Dockerfile
    container_name: academic_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Cấu hình kết nối MySQL thông qua service "db"
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/academic_management_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

     
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - db     # Yêu cầu MySQL khởi động trước
      - redis  # Yêu cầu Redis khởi động trước luôn mới cho Backend chạy
    networks:
      - app_network

# Định nghĩa độc lập khu vực lưu trữ dữ liệu
volumes:
  db_data:
  redis_data: # Khai báo volume cho Redis

# Mạng nội bộ kết nối cả 3 container (db, redis, api) với nhau
networks:
  app_network:
    driver: bridge